travel_gpt: 
  # Record interface access history 
  access_record: true 
 
open_ai:
  provider: "gemini"  # hoặc "gemini" để chọn AI provider
  timeout: 60
  api_key: ""
  travel_content: "Hi!\n\nI'm TravelGPT, your personal travel assistant.\n\nI can help with where you plan to go, how long you'll travel, and any other preferences or special circumstances."
  sys_content: "You are now a travel expert, master of travel time planning. Help me plan specific travel schedules, itinerary arrangements, recommend attractions, activities, restaurant suggestions, estimate average budget per person."
  model: "gpt-4"
  proxy: ""

gao_de: 
  # Gaode Map API KEY 
  api_key: "" 
  # Gaode API URL 
  api_url: "https://restapi.amap.com/v3" 
  # Gaode navigation URL 
  nva_url: "https://m.amap.com/navi" 
 
data_source: 
  # mysql、postgre、sqlite 
  type: "sqlite" 
  mysql_url: "mysql://root:123456@localhost:3307/test?charset=utf8" 
  postgre_url: "postgresql+psycopg2://root:123456@localhost:3307/test" 
  sqlite_url: "sqlite:///DB.sqlite" 
  log_level: "debug" 
 
redis: 
  host: localhost 
  port: 6379 
  pwd: 
  db: 0 
 
reset_pwd: 
  url: http://localhost:8089/test 

gemini:
  api_key: ""
  model: "gemini-2.0-flash"
  timeout: 60